### ISSUE TITLE
Printing accuracy and resulting shaper cuts: add registration marks

### ISSUE THREAD

**Issue by marvingreenberg** [ShyftXero/ShaperPaper#1]
I thought about this problem - planned to do something similar, but I've come across one discussion in Shaper community where someone described resulting inaccuracy in the cuts (using photocopies), and the Shaper folks themselves have discouraged this.  I think the problem is how laser printers print - a piece of paper gets fed past a drum driven by rollers.  Minor variations in the feed speed or imperfections in the rollers will cause variations in one direction.  I think your approach using Processing has advantages since it removes the inaccuracy from the scan, and only has the inaccuracy of the print.  I googled around for "dimensionally accurate laser printing" (e.g., http://forum.designcadcommunity.com/index.php?topic=6083.0)  One comment suggested using a plotter. 

It would be interesting to create some tests using a few standard SVG files, and characterize the resultant cuts, documenting the specific printer used.    It would also be interesting to add some registration marks on your plots, of known distance, so after printing you could check that the marks were, say, exactly 250 mm apart in the long direction.  An error of 0.5% would then be a little over a mm, which should be measurable.

**Comment by ShyftXero** [comment]
I added registration marks to the code and the generated pdf for download. They should be about 10mm apart along the vertical axis. Have you tried the paper yet?

**Comment by marvingreenberg** [comment]
It's on my list.  I've gotten distracted, haven't been doing anything with my SO for a while.  I'm only a hobbyist, so doing things with SO competes with all the stuff I'm SUPPOSED to be doing.  I do "plan" to test the accuracy of these sorts of generated PDFs.  My main concern is not the cost of tape - I'd be happier if the tape was $10 a roll instead of $18, but using some work setups that reuse tape, I think the cost is bearable.  My main concern is if Shaper goes feet up, this expensive tool becomes a doorstop.  Thanks for the work.
